api_platform:
    title: 'Symfony - TODO LIST API Platform REST API'
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']  # Ajout du support pour le format JSON standard
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/json']
    swagger:
        versions: [3]
